# Generated by Django 4.1.2 on 2022-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='aciklama',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='makale',
            name='baslik',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='makale',
            name='sehir',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='makale',
            name='yazar',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AlterField(
            model_name='makale',
            name='aktif',
            field=models.BooleanField(),
        ),
    ]
