# Generated by Django 4.1.2 on 2022-11-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_makale_aciklama_makale_baslik_makale_sehir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='yayinlanma_Tarihi',
            new_name='yayinlanma_tarihi',
        ),
    ]
