# Generated by Django 4.1.3 on 2022-11-14 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bas_tarih',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 17, 15, 55, 945493)),
        ),
        migrations.AlterField(
            model_name='task',
            name='bit_tarih',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 17, 15, 55, 945493)),
        ),
    ]
