# Generated by Django 4.1.3 on 2022-11-14 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotasks', '0002_alter_task_bas_tarih_alter_task_bit_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bas_tarih',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 17, 19, 22, 208206)),
        ),
        migrations.AlterField(
            model_name='task',
            name='bit_tarih',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 17, 19, 22, 208206)),
        ),
        migrations.AlterField(
            model_name='task',
            name='oncelik',
            field=models.CharField(choices=[('Çok önemli', 'çok önemli'), ('Önemli', 'önemli'), ('Normal', 'normal'), ('aciliyeti yok', 'aciliyeti yok'), ('önemsiz', 'önemsiz')], default='Normal', max_length=13),
        ),
    ]
